language: node_js

before_script:
  - npm install -g grunt
  - npm install -g grunt-cli
  - npm install -g grunt-ts
  - npm install -g matchdep
  - npm install -g mocha
  - npm install

script: mocha ./test/storeAndGetLinks.js

node_js:
  - "5.3"
